# Generated by Django 5.2.4 on 2025-11-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_freezingentrylocalitem_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezingentrylocal',
            name='total_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='freezingentryspot',
            name='total_kg',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
        migrations.AlterField(
            model_name='freezingentrytenant',
            name='total_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='returntenant',
            name='total_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='shed',
            name='capacity_per_day_kg',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
        migrations.AlterField(
            model_name='spotpurchaseitem',
            name='boxes',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenantbill',
            name='total_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tenantstock',
            name='available_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tenantstock',
            name='original_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
