# Generated by Django 5.2.4 on 2025-11-10 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_freezingentrylocal_total_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preshipmentworkoutitem',
            name='peeling_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemtype'),
        ),
    ]
