# Generated by Django 5.2.4 on 2025-11-15 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_preshipmentworkoutitem_peeling_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheditem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sheditem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='glazepercentage',
            name='percentage',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
