# Generated by Django 5.2.4 on 2025-11-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_sheditem_created_at_sheditem_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shed',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
