# Generated by Django 5.2.4 on 2025-11-20 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_shed_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetransferitem',
            name='peeling_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.itemtype'),
        ),
    ]
