# Generated by Django 5.2.4 on 2025-09-29 07:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0028_alter_species_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processingoverhead',
            old_name='freezing_expense',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='processingoverhead',
            name='other_expense',
        ),
        migrations.AddField(
            model_name='freezingcategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='freezingcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='processingoverhead',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='processingoverhead',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantfreezingtariff',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tenantfreezingtariff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='freezingcategory',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='freezingcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
