# Generated by Django 5.0.6 on 2025-10-02 14:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0029_rename_freezing_expense_processingoverhead_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShipmentDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(max_length=100)),
                ('port_of_loading', models.CharField(max_length=150)),
                ('port_of_discharge', models.CharField(max_length=150)),
                ('final_destination', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('hs_code', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer_order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_order_date', models.DateField(blank=True, null=True)),
                ('exporter_name', models.CharField(default='AM FISHERIES', max_length=200)),
                ('exporter_address', models.TextField(blank=True, null=True)),
                ('exporter_iec_code', models.CharField(blank=True, max_length=50, null=True)),
                ('exporters_ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('steamer_line_no', models.CharField(blank=True, max_length=100, null=True)),
                ('customs_seal_no', models.CharField(blank=True, max_length=100, null=True)),
                ('container_no', models.CharField(blank=True, max_length=100, null=True)),
                ('rex_reg_no', models.CharField(blank=True, max_length=100, null=True)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('country_of_origin', models.CharField(default='COCHIN, INDIA', max_length=100)),
                ('country_of_destination', models.CharField(max_length=100)),
                ('gstin_number', models.CharField(blank=True, max_length=50, null=True)),
                ('igst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount_after_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('processed_by', models.TextField(blank=True, null=True)),
                ('declaration_text', models.TextField(blank=True, null=True)),
                ('bank_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itembrand')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_entries', to='adminapp.buyer')),
                ('freezing_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.freezingcategory')),
                ('glaze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.glazepercentage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_entries_items', to='adminapp.item')),
                ('item_quality', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemquality')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.packingunit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesEntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartons', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_usd_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.itemgrade')),
                ('peeling_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.itemtype')),
                ('sales_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adminapp.salesentry')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.species')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
