# Generated by Django 5.2.4 on 2025-10-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0030_buyer_shipmentdestination_salesentry_salesentryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(max_length=30),
        ),
    ]
