# Generated by Django 5.2.4 on 2025-10-10 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0031_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezingentrylocalitem',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itembrand'),
        ),
        migrations.AlterField(
            model_name='freezingentrylocalitem',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemgrade'),
        ),
        migrations.AlterField(
            model_name='freezingentrylocalitem',
            name='peeling_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemtype'),
        ),
        migrations.AlterField(
            model_name='freezingentrylocalitem',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.species'),
        ),
        migrations.AlterField(
            model_name='freezingentryspotitem',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itembrand'),
        ),
        migrations.AlterField(
            model_name='freezingentryspotitem',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemgrade'),
        ),
        migrations.AlterField(
            model_name='freezingentryspotitem',
            name='peeling_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemtype'),
        ),
        migrations.AlterField(
            model_name='freezingentryspotitem',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.species'),
        ),
    ]
