# Generated by Django 5.2.4 on 2025-10-13 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0032_alter_freezingentrylocalitem_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='peelingtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemtype'),
        ),
    ]
