# Generated by Django 5.2.4 on 2025-10-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0033_stock_peelingtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='peelingtype',
            new_name='peeling_type',
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('store', 'item', 'brand', 'item_quality', 'unit', 'glaze', 'species', 'item_grade', 'peeling_type')},
        ),
    ]
