# Generated by Django 5.2.4 on 2025-10-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0035_freezingentrytenantitem_peeling_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantStock',
        ),
    ]
