# Generated by Django 5.2.4 on 2025-10-15 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0036_delete_tenantstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_slab', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available_c_s', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('original_slab', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('original_c_s', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('original_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itembrand')),
                ('freezing_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.freezingcategory')),
                ('glaze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.glazepercentage')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemgrade')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.item')),
                ('item_quality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemquality')),
                ('peeling_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemtype')),
                ('processing_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.processingcenter')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.species')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.store')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.packingunit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
