# Generated by Django 5.2.4 on 2025-10-15 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0037_tenantstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantstock',
            name='tenant_company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tenant'),
        ),
        migrations.AddIndex(
            model_name='tenantstock',
            index=models.Index(fields=['tenant_company_name', 'item'], name='adminapp_te_tenant__38d0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantstock',
            index=models.Index(fields=['processing_center', 'store'], name='adminapp_te_process_0d1479_idx'),
        ),
    ]
