# Generated by Django 5.2.4 on 2025-10-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0039_alter_returntenantitem_original_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returntenantitem',
            name='original_item',
        ),
        migrations.AlterField(
            model_name='returntenant',
            name='return_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete')], default='incomplete', max_length=50),
        ),
    ]
