# Generated by Django 5.2.4 on 2025-10-16 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0040_remove_returntenantitem_original_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preshipmentworkoutitem',
            name='item_quality',
        ),
        migrations.AddField(
            model_name='preshipmentworkout',
            name='item_quality',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemquality'),
        ),
    ]
