# Generated by Django 5.2.4 on 2025-10-16 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0041_remove_preshipmentworkoutitem_item_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preshipmentworkout',
            name='item_quality',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='adminapp.itemquality'),
            preserve_default=False,
        ),
    ]
