# Generated by Django 5.2.4 on 2025-10-16 17:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0043_purchasingsupervisor_commission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasingsupervisor',
            name='commission',
        ),
        migrations.AlterField(
            model_name='purchasingsupervisor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='SupervisorCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='adminapp.purchasingsupervisor')),
            ],
        ),
    ]
