# Generated by Django 5.2.4 on 2025-10-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0044_remove_purchasingsupervisor_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasingsupervisor',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SupervisorCommission',
        ),
    ]
