# Generated by Django 5.2.4 on 2025-10-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0045_purchasingsupervisor_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasingsupervisor',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
