# Generated by Django 5.2.4 on 2025-10-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0047_alter_purchasingsupervisor_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasingsupervisor',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
