# Generated by Django 5.2.4 on 2025-10-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0048_alter_purchasingsupervisor_mobile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('store', 'item', 'brand', 'item_quality', 'unit', 'glaze', 'species', 'item_grade', 'peeling_type', 'freezing_category')},
        ),
    ]
