# Generated by Django 5.2.4 on 2025-10-28 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0050_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezingentrytenantitem',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.species'),
        ),
        migrations.AlterField(
            model_name='itemgrade',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.species'),
        ),
        migrations.AlterField(
            model_name='preshipmentworkoutitem',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.species'),
        ),
        migrations.AlterField(
            model_name='returntenantitem',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.species'),
        ),
        migrations.AlterField(
            model_name='salesentryitem',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.species'),
        ),
        migrations.AlterField(
            model_name='tenantstock',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.species'),
        ),
    ]
