# Generated by Django 5.2.4 on 2025-10-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0051_alter_freezingentrytenantitem_species_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgrade',
            name='order_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
